In [1]:
import pandas as pd

In [2]:
data=pd.read_csv(r"C:\Users\shaziya\Downloads\-international-trade-data--main\-international-trade-data--main\FDI data.csv")

In [3]:
data

,Sector,2000-01,2001-02,2002-03,2003-04,2004-05,2005-06,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17
0,METALLURGICAL INDUSTRIES,22.69,14.14,36.61,8.11,200.38,149.13,169.94,1175.75,959.94,419.88,1098.14,1786.14,1466.23,567.63,359.34,456.31,1440.18
1,MINING,1.32,6.52,10.06,23.48,9.92,7.40,6.62,444.36,34.16,174.40,79.51,142.65,57.89,12.73,684.39,520.67,55.75
2,POWER,89.42,757.44,59.11,27.09,43.37,72.69,157.15,988.68,907.66,1271.79,1271.77,1652.38,535.68,1066.08,707.04,868.80,1112.98
3,NON-CONVENTIONAL ENERGY,0.00,0.00,1.70,4.14,1.27,1.35,2.44,58.82,125.88,622.52,214.40,452.17,1106.52,414.25,615.95,776.51,783.57
4,COAL PRODUCTION,0.00,0.00,0.00,0.04,0.00,9.14,1.30,14.08,0.22,0.00,0.00,0.00,0.00,2.96,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,PRINTING OF BOOKS (INCLUDING LITHO PRINTING IN...,0.00,0.00,6.30,0.00,0.06,9.90,20.04,35.54,31.61,70.51,36.63,47.39,14.34,113.78,72.58,122.81,53.17
59,COIR,0.00,0.00,0.00,0.00,0.47,0.59,0.04,0.01,0.00,0.25,0.10,0.55,0.15,0.54,1.36,0.00,0.00
60,CONSTRUCTION (INFRASTRUCTURE) ACTIVITIES,0.00,0.00,0.00,0.00,0.00,0.93,64.06,182.92,172.70,324.56,675.07,386.28,283.89,485.37,870.25,4510.71,1860.73
61,"CONSTRUCTION DEVELOPMENT: Townships, housing, ...",24.33,51.75,36.10,47.04,152.06,228.71,1392.95,3887.33,4657.51,5466.13,1663.03,3140.78,1332.49,1226.05,769.14,112.55,105.14
62,MISCELLANEOUS INDUSTRIES,832.07,221.37,218.76,235.48,121.83,164.76,304.87,528.42,1549.70,1147.56,1475.97,813.38,229.49,468.74,765.88,668.77,296.40